import { type AppUiTheme } from "../types";

export const etherealTheme: AppUiTheme = {
  chrome: {
    accentColor: "#1A1A1A",
    titleBarBackground: "#FAF6F0",
    titleBarColor: "#1A1A1A",
    titleBarBorderBottom: "1px dotted #C4B8A8",
    titleBarHeight: 36,
    titleFontSize: 11,
    titleFontWeight: 600,
    titleLetterSpacing: "0.12em",
    titleTextTransform: "uppercase",
    titleBarFontFamily: 'var(--font-roboto-mono), ui-monospace, monospace',
    titleBarClassName: "pointillism-title-bar",
    windowClassName: "pointillism-window",
    controlsClassName: "pointillism-window-controls",
    windowBorder: "1px solid #1A1A1A",
    windowBackground: "#F5EDE3",
    windowShadow: "4px 4px 0 rgba(26, 26, 26, 0.12)",
    contentBackground: "#F5EDE3",
    controls: {
      width: 36,
      borderLeft: "1px dotted #C4B8A8",
      minimize: {
        background: "#FAF6F0",
        color: "#6B5E54",
      },
      maximize: {
        background: "#FAF6F0",
        color: "#6B5E54",
      },
      close: {
        background: "#FAF6F0",
        color: "#1A1A1A",
      },
    },
  },
  content: {
    background: "#F5EDE3",
    color: "#1A1A1A",
    fontFamily: 'var(--font-roboto-mono), ui-monospace, monospace',
    className: "pointillism-app",
    vars: {
      "app-bg": "#F5EDE3",
      "app-card": "#FAF6F0",
      "app-card-alt": "#1A1A1A",
      "app-fg": "#1A1A1A",
      "app-fg-inv": "#FAF6F0",
      "app-muted": "#6B5E54",
      "app-ink": "#1A1A1A",
      "app-pink": "#F4C4C4",
      "app-pink-soft": "#FBEBEB",
      "app-peach": "#E8C4A8",
      "app-peach-soft": "#F5EADF",
      "app-sage": "#8FA888",
      "app-sage-soft": "#E8EFE5",
      "app-slate": "#9AABB5",
      "app-slate-soft": "#E4EAED",
      "app-border": "#C4B8A8",
      "app-shadow": "none",
      "app-radius": "0",
      "app-radius-sm": "0",
    },
  },
};
